# Important Python packages

## Numpy

In [1]:
import numpy as np

Numpy contains almost everything you can imagine regarding mathematics and matric/vector operations. 

In [4]:
vector_length = 5
print(np.zeros(vector_length))
print(np.ones(vector_length))

[ 0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.]


Make a custom array with values which are all complex numbers.

In [17]:
print(np.array([1, 2, 3]), '\n')
print(np.array([(1, 2, 3), (4, 5, 6)]), '\n')
print(np.array([1, 2, 3, 4, 5, 6], dtype = complex), '\n')

[1 2 3] 

[[1 2 3]
 [4 5 6]] 

[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j] 



## Matplotlib