In [14]:
import numpy as np
from numpy import genfromtxt
from sklearn.cross_validation import train_test_split
import matplotlib.pyplot as plt
from sklearn.svm import SVC
#%matplotlib inline

In [16]:
my_data = genfromtxt('datanew.csv', delimiter=',')

X, Y = my_data[:, 1:4], my_data[:, 4]

print(X.shape)
print(Y.shape)

print(X[0:3, :])
print(Y[0:3])

(162501, 3)
(162501,)
[[ 1502.  2215.  2153.]
 [ 1667.  2072.  2047.]
 [ 1611.  1957.  1906.]]
[ 1.  1.  1.]


In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33)

print(y_train.shape)
print(X_train.shape)

X_train = X_train[0:5000]
y_train = y_train[0:5000]

X_test = X_test[0:1000]
y_test = y_test[0:1000]

print(y_train)

(108875,)
(108875, 3)
[ 4.  7.  7. ...,  7.  7.  5.]


In [18]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
from numpy import where

# Plots 2 features, with an output, shows the decision boundary
def plot3D(x, y):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    pos = where(y == 1)
    neg = where(y == 0)
    
    color = ['r', 'b', 'y', 'k', 'g', 'c', 'm']
    
    for i in range(30):
        ax.scatter(x[i, 0], x[i, 1],x[i, 2], marker='o', c=color[int(y[i])-1])
    #ax.scatter(x[:,1], x[:,2], y)
    ax.set_xlabel('X Label')
    ax.set_ylabel('Y Label')
    ax.set_zlabel('Z Label')

    axes = plt.axis()
    plt.show()
    
plot3D(X_train, y_train)

In [11]:
from sklearn.svm import SVC
clf = SVC()
clf.fit(X_train, y_train)

clf.score(X_test, y_test)

0.64500000000000002

In [12]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.77000000000000002

In [13]:
from sklearn.ensemble import RandomForestClassifier 

forest = RandomForestClassifier(n_estimators = 100)

forest = forest.fit(X_train, y_train)
forest.score(X_test, y_test)

0.83699999999999997