In [1]:
import numpy as np
from numpy import genfromtxt
from sklearn.cross_validation import train_test_split
import matplotlib.pyplot as plt
from sklearn.svm import SVC
#%matplotlib inline

C:\Users\Karim\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


# Import the data

The data is saved in a comma seperated file using the delimeter ','. This means that each data instance is seperated by a comma. 

In [2]:
my_data = genfromtxt('datanew.csv', delimiter=',')

X, Y = my_data[:, 1:4], my_data[:, 4]

print(X.shape)
print(Y.shape)

print(X[0:3, :])
print(Y[0:3])

(162501, 3)
(162501,)
[[ 1502.  2215.  2153.]
 [ 1667.  2072.  2047.]
 [ 1611.  1957.  1906.]]
[ 1.  1.  1.]


# Split the data

Split the data into train/test set. 

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33)

print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

#X_train = X_train[0:5000]
#y_train = y_train[0:5000]

#X_test = X_test[0:1000]
#y_test = y_test[0:1000]

print(y_train)

(108875, 3)
(108875,)
(53626, 3)
(53626,)
[ 4.  7.  7. ...,  7.  1.  7.]


# Visualize the data

Visualize the 3-dimensional data to see how the labels are grouped. We can see that their is no clear linearly differentiable seperator of the data. 

In [ ]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
from numpy import where

# Plots 2 features, with an output, shows the decision boundary
def plot3D(x, y):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    pos = where(y == 1)
    neg = where(y == 0)
    
    color = ['r', 'b', 'y', 'k', 'g', 'c', 'm']
    
    for i in range(30):
        ax.scatter(x[i, 0], x[i, 1],x[i, 2], marker='o', c=color[int(y[i])-1])
    #ax.scatter(x[:,1], x[:,2], y)
    ax.set_xlabel('X Label')
    ax.set_ylabel('Y Label')
    ax.set_zlabel('Z Label')

    axes = plt.axis()
    plt.show()
    
plot3D(X_train, y_train)

# Support Vector Classifier (SVC)

In [4]:
from sklearn.svm import SVC
clf = SVC()
clf.fit(X_train[0:5000], y_train[0:5000])

clf.score(X_test, y_test)

0.65908328049826581

# Decision Trees

In [5]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.78144929698280685

# Random Forests

In [6]:
from sklearn.ensemble import RandomForestClassifier 

forest = RandomForestClassifier(n_estimators = 100)

forest = forest.fit(X_train, y_train)
forest.score(X_test, y_test)

0.83892141871480252